# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"URLs": "00_utils.ipynb",
         "to_hhmmss": "00_utils.ipynb",
         "to_secs": "00_utils.ipynb",
         "trim_video": "00_utils.ipynb",
         "check_resolution": "00_utils.ipynb",
         "check_fps": "00_utils.ipynb",
         "change_audio_format": "00_utils.ipynb",
         "trim_audio": "00_utils.ipynb",
         "DeepWord": "01_core.ipynb"}

modules = ["utils.py",
           "core.py"]

doc_url = "https://deepword18.github.io/dword/"

git_url = "https://github.com/deepword18/dword/tree/master/"

def custom_doc_links(name): return None
