# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"crop_video": "00_utils.ipynb",
         "play_video": "00_utils.ipynb"}

modules = ["utils.py"]

doc_url = "https://deepword18.github.io/dword/"

git_url = "https://github.com/deepword18/dword/tree/master/"

def custom_doc_links(name): return None
