# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_credits": "00_utils.ipynb",
         "get_video_list": "00_utils.ipynb",
         "download_video": "00_utils.ipynb",
         "download_all_videos": "00_utils.ipynb",
         "download_youtube_video": "00_utils.ipynb",
         "text_to_speech": "00_utils.ipynb",
         "trim_video": "00_utils.ipynb",
         "get_resolution": "00_utils.ipynb",
         "get_fps": "00_utils.ipynb",
         "trim_audio": "00_utils.ipynb",
         "generate_video": "01_core.ipynb"}

modules = ["utils.py",
           "core.py"]

doc_url = "https://deepword18.github.io/dword/"

git_url = "https://github.com/deepword18/dword/tree/master/"

def custom_doc_links(name): return None
